### ISSUE TITLE
example: ビルドが通るかどうかをCIでテストする

### ISSUE THREAD

**Issue by Qs-F** [4-design/for-ui#1177]
- 使う側でのテストとしても利用する

**Comment by Qs-F** [comment]
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at Ie (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/@4design/for-ui/dist/commonjs/for-ui.js:1:26255)
    at div
    at IndexPage
    at StyledEngineProvider (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/@mui/styled-engine/node/StyledEngineProvider/StyledEngineProvider.js:26:5)
    at MyApp (webpack-internal:///./pages/_app.tsx:20:18)
    at StyleRegistry (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/styled-jsx/dist/index/index.js:449:36)
    at PathnameContextProviderAdapter (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/next/dist/shared/lib/router/adapters.js:74:11)
    at AppContainer (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/next/dist/server/render.js:332:29)
    at AppContainerWithIsomorphicFiberStructure (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/next/dist/server/render.js:368:57)
    at div
    at Body (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/next/dist/server/render.js:666:21)
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
error - Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6043:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderHostElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5642:3)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5952:5)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderIndeterminateComponent (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5785:7)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5946:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderNode (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6259:12)
    at renderChildrenArray (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6211:7)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6141:7)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5971:9)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14)
    at renderContextProvider (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5920:3)
    at renderElement (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6017:11)
    at renderNodeDestructiveImpl (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6104:11)
    at renderNodeDestructive (/Users/qsf/Develop/go/src/github.com/4-design/for-ui/example/nextjs-app/node_modules/react-dom/cjs/react-dom-server.browser.development.js:6076:14) {
  digest: undefined
}
```
